// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: membership.sql

package pg

import (
	"context"
)

const cancelMembership = `-- name: cancelMembership :exec
UPDATE memberships
SET membership_status='INACTIVE'
WHERE member_id=$1 AND title=$2
`

type cancelMembershipParams struct {
	MemberID int32
	Title    string
}

func (q *Queries) cancelMembership(ctx context.Context, arg cancelMembershipParams) error {
	_, err := q.db.Exec(ctx, cancelMembership, arg.MemberID, arg.Title)
	return err
}

const createMembership = `-- name: createMembership :exec
INSERT INTO memberships (member_id, title, membership_status)
VALUES ($1, $2, 'ACTIVE')
`

type createMembershipParams struct {
	MemberID int32
	Title    string
}

func (q *Queries) createMembership(ctx context.Context, arg createMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.MemberID, arg.Title)
	return err
}
