// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package pg

import ()

type MemberTrained struct {
	TrainerID int32
	MemberID  int32
}

type Role struct {
	RoleID   int32
	RoleName string
}

type TrainerInterest struct {
	TrainerID int32
	Interest  string
}

type User struct {
	UserID       int32
	Username     string
	UserPassword string
	FirstName    string
	LastName     string
	UserEmail    string
}

type UserRole struct {
	UserRolesID int32
	UserID      int32
	RoleID      int32
}
