// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user.sql

package pg

import (
	"context"
)

const createUser = `-- name: createUser :one
INSERT INTO users (username, user_email, user_password, first_name, last_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING user_id
`

type createUserParams struct {
	Username     string
	UserEmail    string
	UserPassword string
	FirstName    string
	LastName     string
}

func (q *Queries) createUser(ctx context.Context, arg createUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.UserEmail,
		arg.UserPassword,
		arg.FirstName,
		arg.LastName,
	)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const getAllUsers = `-- name: getAllUsers :many
SELECT user_id, username, user_password, first_name, last_name, user_email FROM users
`

func (q *Queries) getAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.UserPassword,
			&i.FirstName,
			&i.LastName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: getUserByEmail :one
SELECT user_id, user_email, first_name, last_name
FROM users
WHERE user_email = $1
`

type getUserByEmailRow struct {
	UserID    int32
	UserEmail string
	FirstName string
	LastName  string
}

func (q *Queries) getUserByEmail(ctx context.Context, userEmail string) (getUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, userEmail)
	var i getUserByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getUserByID = `-- name: getUserByID :one
SELECT user_id, user_email, first_name, last_name
FROM users
WHERE user_id = $1
`

type getUserByIDRow struct {
	UserID    int32
	UserEmail string
	FirstName string
	LastName  string
}

func (q *Queries) getUserByID(ctx context.Context, userID int32) (getUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i getUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getUserByUsername = `-- name: getUserByUsername :one
SELECT user_id, user_email, first_name, last_name
FROM users
WHERE username = $1
`

type getUserByUsernameRow struct {
	UserID    int32
	UserEmail string
	FirstName string
	LastName  string
}

func (q *Queries) getUserByUsername(ctx context.Context, username string) (getUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i getUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}
